### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [Sehyn/RTSP_ImouRanger2C#1]
Hi there, 1st of all thanks for this awesome work !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under [VIDEO resources](https://github.com/forart/HyMPS#-1 ) \ [RTSP](https://github.com/forart/HyMPS/blob/main/Video/RTSP.md#--) \ [Generic](https://github.com/forart/HyMPS/blob/main/Video/RTSP.md#generic-)), can you please add a GH-compliant license file for it ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://badgen.net/github/license/Sehyn/RTSP_ImouRanger2C)
(badge-generator URL: https://badgen.net/github/license/Sehyn/RTSP_ImouRanger2C)

You can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Hope that helps/inspires !

**Comment by MarcoRavich** [comment]
Bump (request updated).

**Comment by MarcoRavich** [comment]
Bump 2 (request updated again).

**Comment by Sehyn** [comment]
> Bump 2 (request updated again).

Sorry for very very late reply, it is now fixed and I'll also update my code many things have been added and saved locally :)

**Comment by MarcoRavich** [comment]
Hi there, thanks for the update.

We will close this issue as soon as the badge is successfully generated (probably within 24 hours).

In the meantime, we invite you to check potentially useful resources we've collected on the page above.

Happy coding !
